# Generated by Django 4.0.3 on 2023-07-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_total_sales_product_totla_sales_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='totla_sales_amount',
            new_name='total_sales_amount',
        ),
    ]
